(define (domain turismomm)
    (:requirements :strips)
    (:predicates
        (at ?who ?where)
        (at ?what ?where)
        (is-turist ?who)
        (is-bike ?what)
        (have ?who ?what)
        (have-to-wait5 ?who)
        (waited ?who)
        (is-turistic-point ?where)
        (is-bike-station ?where)
        (visited ?who ?where))
    
    (:action take-bike
        :parameters (?who ?what ?where)
        :precondition (and (is-turist ?who)
                      (is-bike ?what)
                      (at ?who ?where)
                      (at ?what ?where)
                      (waited ?who))
        :effect (and (have ?who ?what)
                (not (at ?what ?where)))
    )
    (:action deliver-bike
        :parameters (?who ?what ?where)
        :precondition (and (is-turist ?who)
                      (is-bike ?what)
                      (have ?who ?what)
                      (at ?who ?where))
        :effect (and (at ?what ?where)
                (at ?who ?where)
                (not (have ?who ?what))
                (have-to-wait5 ?who))
    )
    (:action wait-5minutes
        :parameters (?who)
        :precondition (and (is-turist ?who)
                      (have-to-wait5 ?who))
        :effect(and (waited ?who))
    )

    (:action visit-point
        :parameters (?who ?where)
        :precondition (and (is-turist ?who)
                      (is-turistic-point ?where)
                      (at ?who ?where))
        :effect(visited(?who ?where))                  
    )
)